import React, { useState, useEffect } from 'react';
import WeatherRadar from './WeatherRadar';
import 'leaflet/dist/leaflet.css'; // Ensure leaflet CSS is imported

function App() {
  const [weatherData, setWeatherData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Fetches the static JSON generated by GitHub Actions
    fetch('/forecast.json')
      .then(res => res.json())
      .then(data => {
        setWeatherData(data);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to load forecast data:", err);
        setLoading(false);
      });
  }, []);

  if (loading) return <div className="p-10 text-xl font-bold">Loading Swiss Radar Data...</div>;
  if (!weatherData) return <div className="p-10 text-xl text-red-600">Error loading data.</div>;

  return (
    <div className="App w-full h-screen">
      <WeatherRadar precalculatedData={weatherData} />
    </div>
  );
}

export default App;

